/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NNDepParser */

#ifndef _Included_NNDepParser
#define _Included_NNDepParser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
