/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StanfordParser */

#ifndef _Included_StanfordParser
#define _Included_StanfordParser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
